# Deployment Target
platform :ios, '8.0'

# Add pods as frameworks so we could add obj-c and swift 3.0 pods
use_frameworks!


target 'ObjectMapperAdditions_Example' do
    pod 'APExtensions'
    pod 'ObjectMapper'
    pod 'ObjectMapperAdditions', :path => '../'

    target 'ObjectMapperAdditions_Tests' do
        inherit! :search_paths

        pod 'Quick'
        pod 'Nimble'
    end
end


post_install do |installer|
    # Add podInstall.command and podUpdate.command shell scripts to Pods project
    pods_project = installer.pods_project
    pods_project.new_file "../podInstall.command"
    pods_project.new_file "../podUpdate.command"
end
