source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Artsy/Specs.git'

# Deployment Target
platform :ios, '11.0'

# Add pods as frameworks so we could add obj-c and swift 3.0 pods
use_frameworks!


target 'ObjectMapperAdditions_Example' do
  pod 'APExtensions', :git => 'https://github.com/APUtils/APExtensions'
  pod 'ObjectMapperAdditions', :path => '../'
  
  target 'ObjectMapperAdditions_Tests' do
    inherit! :search_paths
    
    pod 'Quick'
    pod 'Nimble'
  end
end



post_install do |installer|
  # Add podInstall.command and podUpdate.command shell scripts to Pods project
  pods_project = installer.pods_project
  pods_project.new_file "../Scripts/Cocoapods/podInstall.command"
  pods_project.new_file "../Scripts/Cocoapods/podUpdate.command"
  
  # Silence Pods project warning
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED'] = 'YES'
  end
end
